# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Jsoftware.J.9.6
PackageVersion: 9.6.0-beta1
Platform:
- Windows.Desktop
InstallModes:
- silent
FileExtensions:
- ijs
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://www.jsoftware.com/download/j9.6/install/j9.6.0-beta1_win64.exe
  InstallerSha256: d87296b8b77480a1781dfb20dd9ae82a0284cc27c80052ca74f64a647a2b63ae
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://www.jsoftware.com/download/j9.6/install/j9.6_win64.exe
  InstallerSha256: d87296b8b77480a1781dfb20dd9ae82a0284cc27c80052ca74f64a647a2b63ae
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.4.0
